# Generated by Django 5.2 on 2025-05-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel',
            field=models.CharField(blank=True, default='00000000000', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user_name',
            field=models.CharField(default='padrao', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
